### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by 0x000015** [anaemicelle/tf2bd#3]
https://github.com/anaemicelle/tf2bd/blob/d6389ea585bddc3c800eb33b0eafafc25453a759/playerlist.sterling.json#L668

Removal of the extra comma will fix the issue. Suggest using a JSON validator to avoid this issue later on

**Comment by anaemicelle** [comment]
Good call. I fixed it. Usually I'm pretty good at dealing with stray commas...
