### ISSUE TITLE
Falsely accused - 15

### ISSUE THREAD

**Issue by BowrainDash** [anaemicelle/tf2bd#4]
"proof: Very unskilled rage hacker--took 5 aimbotted stickies to kill a medic in a corner, forcing crits, aimbotting stickies and pipes"
Lol, what kind of proof is that? No screenshots, videos, or witnesses? What a joke.
Here's his RGL account: https://rgl.gg/Public/PlayerProfile?p=76561199143903489&r=40
I personally know him and he's not a cheater, he plays competitive at a high level.

**Comment by anaemicelle** [comment]
We don't unmark cheaters.
